routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('student/create','admin\UsersController@createS')->name('stc');
Route::post('student/create','admin\UsersController@student')->name('student.create');
Route::get('/admin', 'AdminController@index')->middleware('auth');
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::resource('/users', 'admin\UsersController');
    Route::get('/users/{id}/imper', 'admin\UsersController@imper')->name('imper');
    Route::get('/stopimper', 'admin\UsersController@stopImper')->name('stopImper');
    Route::resource('exam1s', 'Exam1Controller');
    Route::resource('fund1s', 'Fund1Controller');
    Route::resource('certms', 'CertmController');
    Route::resource('unilives', 'UnilifeController');
    Route::resource('marks', 'MarkController');
    Route::resource('grads', 'GradController');
    Route::resource('bloods', 'BloodController');
    Route::resource('items', 'ItemController');
    Route::resource('seconds', 'secondController');
    Route::resource('termens', 'TermenController');
    Route::resource('gradcerts', 'GradcertController');
    Route::resource('sregests', 'SregestController');
    Route::resource('manuals', 'ManualController');
    Route::resource('rejects', 'RejectController');
    Route::resource('erejects', 'ErejectController');
    Route::resource('attends', 'AttendController');
    Route::resource('lifens', 'LifenController');
    Route::resource('markns', 'MarknController');
    Route::resource('gradorders', 'GradorderController');
    Route::resource('gradcs', 'GradcController');
    Route::resource('hcerts', 'hcertController');
});Route::resource('stopregs', 'StopregController');

app/Sregest.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Sregest extends Model
{
    protected $guarded = [''];
}

app/Http/Controllers/SregestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
use App\Sregest;
use Gate;

class SregestController extends Controller
{
    public function index()
    {
        $sregests = Sregest::orderBy('id')->paginate(6);
        return view('sregests.index', compact('sregests'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required|min:3',
            'dad' => 'required',
            'section' => 'required',
            'year' => 'required',
            'uniId' => 'required',
            'date' => 'required',
            'nation' => 'required',
            'pId' => 'required',
            'stopseason' => 'required',
        ]);

        $mark = Sregest::create([
            'name' => $request->name,
            'dad' => $request->dad,
            'section' => $request->section,
            'year' => $request->year,
            'uniId' => $request->uniId,
            'date' => $request->date,
            'nation' => $request->nation,
            'pId' => $request->pId,
            'stopseason' => $request->stopseason,
            'user_id'=> Auth::user()->id,
        ]);
        toast('Your Sregest was Added successfully !', 'success');
        return redirect(route('sregests.index'));
    }

    public function create()
    {
        return view('sregests.create');
    }

    public function show(Sregest $sregest)
    {
        return view('sregests.show', compact('sregest'));
    }

    public function edit(Sregest $sregest)
    {
        return view('sregests.edit', compact('sregest'));
    }


    public function update(Request $request, Sregest $sregest)
    {
        $vali = $request->validate([
            'name' => 'required|min:3',
        ]);

        $data = $request->only(['name']);
        $sregest->update($data);
        toast('Your sregest was Updated successfully !', 'success');
        return redirect(route('sregests.index'));
    }

    public function destroy( Sregest $sregest)
    {
        $sregest->delete();
        toast('Your sregest was Deleted !', 'warning');
        return redirect(route('sregests.index'));
    }
}

resources/views/sregests/create.blade.php
@extends('layouts.admin')

@section('main')
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-right alert alert-primary ">   استرداد ايقاف تسجيل  </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('sregests.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4 ml-4">
                                <input id="name" type="text" class="form-control " name="name" value="{{ old('name') }}"
                                autocomplete="name">
                                <div> {{$errors->first('name')}} </div>
                            </div>
                            <label for="name" class="col-md-2 col-form-label text-md-right">اسم مقدم الطلب</label>
                        </div>

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4 ml-4">
                                <input id="year" type="text" class="form-control " name="year" value="{{ old('year') }}"
                                autocomplete="year">
                                <div> {{$errors->first('year')}} </div>
                            </div>
                            <label for="year" class="col-md-2 col-form-label text-md-right">السنة </label>
                        </div>

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="uniId" type="text" class="form-control "
                                name="uniId">
                                <div> {{$errors->first('uniId')}} </div>
                            </div>
                            <label for="uniId" class="col-md-2 col-form-label text-md-right"> الرقم الجامعي</label>
                        </div>

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="dad" type="text" class="form-control "
                                name="dad">
                                <div> {{$errors->first('dad')}} </div>
                            </div>
                            <label for="dad" class="col-md-2 col-form-label text-md-right"> اسم الاب</label>
                        </div>
                        
                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="nation" type="text" class="form-control "
                                name="nation">
                                <div> {{$errors->first('nation')}} </div>
                            </div>
                            <label for="nation" class="col-md-2 col-form-label text-md-right"> الجنسية </label>
                        </div>


                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="date" type="text" class="form-control "
                                name="date">
                                <div> {{$errors->first('date')}} </div>
                            </div>
                            <label for="date" class="col-md-2 col-form-label text-md-right"> العام الدراسي</label>
                        </div>
                        
                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="stopseason" type="text" class="form-control "
                                name="stopseason">
                                <div> {{$errors->first('stopseason')}} </div>
                            </div>
                            <label for="stopseason" class="col-md-2 col-form-label text-md-right"> سنة الايقاف </label>
                        </div>

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="pId" type="text" class="form-control "
                                name="pId">
                                <div> {{$errors->first('pId')}} </div>
                            </div>
                            <label for="pId" class="col-md-2 col-form-label text-md-right"> رقم البطاقة الشخصية  </label>
                        </div>

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="section" type="text" class="form-control "
                                name="section">
                                <div> {{$errors->first('section')}} </div>
                            </div>
                            <label for="section" class="col-md-2 col-form-label text-md-right"> القسم  </label>
                        </div>
                        
                        <div class="form-group row mb-0">
                            <div class="col-md-8 ml-4 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    ارسال الطلب
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection