routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('student/create','admin\UsersController@createS')->name('stc');
Route::post('student/create','admin\UsersController@student')->name('student.create');
Route::get('/admin', 'AdminController@index')->middleware('auth');
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::resource('/users', 'admin\UsersController');
    Route::get('/users/{id}/imper', 'admin\UsersController@imper')->name('imper');
    Route::get('/stopimper', 'admin\UsersController@stopImper')->name('stopImper');
    Route::resource('exam1s', 'Exam1Controller');
    Route::resource('fund1s', 'Fund1Controller');
    Route::resource('certms', 'CertmController');
    Route::resource('unilives', 'UnilifeController');
    Route::resource('marks', 'MarkController');
    Route::resource('grads', 'GradController');
    Route::resource('bloods', 'BloodController');
    Route::resource('items', 'ItemController');
    Route::resource('seconds', 'secondController');
    Route::resource('termens', 'TermenController');
    Route::resource('gradcerts', 'GradcertController');
    Route::resource('sregests', 'SregestController');
    Route::resource('manuals', 'ManualController');
    Route::resource('rejects', 'RejectController');
    Route::resource('erejects', 'ErejectController');
    Route::resource('attends', 'AttendController');
    Route::resource('lifens', 'LifenController');
    Route::resource('markns', 'MarknController');
    Route::resource('gradorders', 'GradorderController');
    Route::resource('gradcs', 'GradcController');
    Route::resource('hcerts', 'hcertController');
});Route::resource('stopregs', 'StopregController');

app/Lifen.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Lifen extends Model
{
    protected $guarded = [''];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/LifenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
use App\Lifen;
use Gate;

class LifenController extends Controller
{
    public function index()
    {
        $lifens = Lifen::orderBy('id')->paginate(6);
        return view('lifens.index', compact('lifens'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required|min:3',
            'year' => 'required',
            'section' => 'required',
            'uniId' => 'required',
            'dad' => 'required',
            'firstreg' => 'required',
        ]);

        $unilife = Lifen::create([
            'name' => $request->name,
            'year' => $request->year,
            'section' => $request->section,
            'uniId' => $request->uniId,
            'dad' => $request->dad,
            'firstreg' => $request->firstreg,
            'user_id'=> Auth::user()->id,
        ]);
        toast('Your Lifen was Added successfully !', 'success');
        return redirect(route('lifens.index'));
    }

    public function create()
    {
        return view('lifens.create');
    }

    public function show(Lifen $lifen)
    {
        return view('lifens.show', compact('lifen'));
    }

    public function edit(Lifen $lifen)
    {
        return view('lifens.edit', compact('lifen'));
    }


    public function update(Request $request, Lifen $lifen)
    {
        $vali = $request->validate([
            'name' => 'required|min:3',
        ]);

        $data = $request->only(['name']);
        $lifen->update($data);
        toast('Your lifen was Updated successfully !', 'success');
        return redirect(route('lifens.index'));
    }

    public function destroy( Lifen $lifen)
    {
        $lifen->delete();
        toast('Your lifen was Deleted !', 'warning');
        return redirect(route('lifens.index'));
    }
}

resources/views/lifens/create.blade.php
@extends('layouts.admin')

@section('main')
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-right alert alert-primary ">  طلب الحصول على حياة جامعية   </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('lifens.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4 ml-4">
                                <input id="name" type="text" class="form-control " name="name" value="{{ old('name') }}"
                                autocomplete="name">
                                <div> {{$errors->first('name')}} </div>
                            </div>
                            <label for="name" class="col-md-2 col-form-label text-md-right">اسم مقدم الطلب</label>
                        </div>

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="section" type="section" class="form-control " name="section"
                                value="{{ old('section') }}" autocomplete="section">
                                <div> {{$errors->first('section')}} </div>
                            </div>
                            <label for="section" class="col-md-2 col-form-label text-md-right">القسم</label>
                        </div>
                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="uniId" type="text" class="form-control "
                                name="uniId">
                                <div> {{$errors->first('uniId')}} </div>
                            </div>
                            <label for="uniId" class="col-md-2 col-form-label text-md-right"> الرقم الجامعي</label>
                        </div>

                        
                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="dad" type="text" class="form-control "
                                name="dad">
                                <div> {{$errors->first('dad')}} </div>
                            </div>
                            <label for="dad" class="col-md-2 col-form-label text-md-right">  اسم الاب</label>
                        </div>
                      

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="year" type="text" class="form-control "
                                name="year">
                                <div> {{$errors->first('year')}} </div>
                            </div>
                            <label for="year" class="col-md-2 col-form-label text-md-right">عام التسجيل</label>
                        </div>

                        <div class="form-group row">
                            
                            <div class="col-md-8 ml-4">
                                <input id="firstreg" type="text" class="form-control "
                                name="firstreg">
                                <div> {{$errors->first('firstreg')}} </div>
                            </div>
                            <label for="firstreg" class="col-md-2 col-form-label text-md-right">عام التسجيل لاول مرة </label>
                        </div>
                       
                        <div class="form-group row mb-0">
                            <div class="col-md-8 ml-4 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    ارسال الطلب
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection