routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});



Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


Route::get('student/create','admin\UsersController@createS')->name('stc');
Route::post('student/create','admin\UsersController@student')->name('student.create');
Route::get('/admin', 'AdminController@index')->middleware('auth');
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::resource('/users', 'admin\UsersController');
    Route::get('/users/{id}/imper', 'admin\UsersController@imper')->name('imper');
    Route::get('/stopimper', 'admin\UsersController@stopImper')->name('stopImper');
    Route::resource('exam1s', 'Exam1Controller');
    Route::resource('fund1s', 'Fund1Controller');
    Route::resource('certms', 'CertmController');
    Route::resource('unilives', 'UnilifeController');
    Route::resource('marks', 'MarkController');
    Route::resource('grads', 'GradController');
    Route::resource('bloods', 'BloodController');
    Route::resource('items', 'ItemController');
    Route::resource('seconds', 'secondController');
    Route::resource('termens', 'TermenController');
    Route::resource('gradcerts', 'GradcertController');
    Route::resource('sregests', 'SregestController');
    Route::resource('manuals', 'ManualController');
    Route::resource('rejects', 'RejectController');
    Route::resource('erejects', 'ErejectController');
    Route::resource('attends', 'AttendController');
    Route::resource('lifens', 'LifenController');
    Route::resource('markns', 'MarknController');
    Route::resource('gradorders', 'GradorderController');
    Route::resource('gradcs', 'GradcController');
    Route::resource('hcerts', 'hcertController');
});Route::resource('stopregs', 'StopregController');

app/Gradorder.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Gradorder extends Model
{
    protected $guarded = [''];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/GradorderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
use App\Gradorder;
use Gate;

class GradorderController extends Controller
{
    public function index()
    {
        $gradorders = Gradorder::orderBy('id')->paginate(6);
        return view('gradorders.index', compact('gradorders'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'col' => 'required|min:3',
            'uni' => 'required',
            'special' => 'required',
            'order' => 'required',
            'percent' => 'required',
            'fullname' => 'required',
            'mom' => 'required',
            'nation' => 'required',
            'city' => 'required',
            'phone' => 'required',
            'needs' => 'required',
        ]);

        $gradorder = Gradorder::create([
            'col' => $request->col,
            'uni' => $request->uni,
            'special' => $request->special,
            'order' => $request->order,
            'percent' => $request->percent,
            'mom' => $request->mom,
            'fullname' => $request->fullname,
            'nation' => $request->nation,
            'city' => $request->city,
            'phone' => $request->phone,
            'needs' => $request->needs,
            'user_id'=> Auth::user()->id,
        ]);
        toast('Your Gradorder was Added successfully !', 'success');
        return redirect(route('gradorders.index'));
    }

    public function create()
    {
        return view('gradorders.create');
    }

    public function show(Gradorder $gradorder)
    {
        return view('gradorders.show', compact('gradorder'));
    }

    public function edit(Gradorder $gradorder)
    {
        return view('gradorders.edit', compact('gradorder'));
    }


    public function update(Request $request, Gradorder $gradorder)
    {
        $vali = $request->validate([
            'name' => 'required|min:3',
        ]);

        $data = $request->only(['name']);
        $gradorder->update($data);
        toast('Your gradorder was Updated successfully !', 'success');
        return redirect(route('gradorders.index'));
    }

    public function destroy( Gradorder $gradorder)
    {
        $gradorder->delete();
        toast('Your gradorder was Deleted !', 'warning');
        return redirect(route('gradorders.index'));
    }
}

resources/views/gradorders/create.blade.php
@extends('layouts.admin')

@section('main')
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-right alert alert-primary "> فرز المهندسين الخريجين   </div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('gradorders.store') }}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row">

                                <div class="col-md-8 ml-4 ml-4">
                                    <input id="fullname" type="text" class="form-control " name="fullname"
                                        value="{{ old('fullname') }}" autocomplete="fullname">
                                    <div> {{ $errors->first('fullname') }} </div>
                                </div>
                                <label for="fullname" class="col-md-2 col-form-label text-md-right">الاسم الثلاثي</label>
                            </div>

                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="uni" type="uni" class="form-control " name="uni" value="{{ old('uni') }}"
                                        autocomplete="uni">
                                    <div> {{ $errors->first('uni') }} </div>
                                </div>
                                <label for="uni" class="col-md-2 col-form-label text-md-right">الجامعة</label>
                            </div>

                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="col" type="col" class="form-control " name="col" value="{{ old('col') }}"
                                        autocomplete="col">
                                    <div> {{ $errors->first('col') }} </div>
                                </div>
                                <label for="col" class="col-md-2 col-form-label text-md-right">الكلية</label>
                            </div>



                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="mom" type="mom" class="form-control " name="mom" value="{{ old('mom') }}"
                                        autocomplete="mom">
                                    <div> {{ $errors->first('mom') }} </div>
                                </div>
                                <label for="mom" class="col-md-2 col-form-label text-md-right">اسم الام</label>
                            </div>


                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="special" type="text" class="form-control " name="special">
                                    <div> {{ $errors->first('special') }} </div>
                                </div>
                                <label for="special" class="col-md-2 col-form-label text-md-right"> الاختصاص </label>
                            </div>


                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="order" type="text" class="form-control " name="order">
                                    <div> {{ $errors->first('order') }} </div>
                                </div>
                                <label for="order" class="col-md-2 col-form-label text-md-right"> تسلسل قرار التخرج</label>
                            </div>


                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="percent" type="text" class="form-control " name="percent">
                                    <div> {{ $errors->first('percent') }} </div>
                                </div>
                                <label for="percent" class="col-md-2 col-form-label text-md-right"> المعدل</label>
                            </div>
                           
                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="nation" type="text" class="form-control " name="nation">
                                    <div> {{ $errors->first('nation') }} </div>
                                </div>
                                <label for="nation" class="col-md-2 col-form-label text-md-right"> الجنسية</label>
                            </div>
                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="city" type="text" class="form-control " name="city">
                                    <div> {{ $errors->first('city') }} </div>
                                </div>
                                <label for="city" class="col-md-2 col-form-label text-md-right"> الاقامة</label>
                            </div>
                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="phone" type="text" class="form-control " name="phone">
                                    <div> {{ $errors->first('phone') }} </div>
                                </div>
                                <label for="phone" class="col-md-2 col-form-label text-md-right"> رقم الهاتتف</label>
                            </div>
                            <div class="form-group row">

                                <div class="col-md-8 ml-4">
                                    <input id="needs" type="text" class="form-control " name="needs">
                                    <div> {{ $errors->first('needs') }} </div>
                                </div>
                                <label for="needs" class="col-md-2 col-form-label text-md-right"> رغبات التعيين</label>
                            </div>




                            <div class="form-group row mb-0">
                                <div class="col-md-8 ml-4 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        ارسال الطلب
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection